#../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_vc2  topology=fattree traffic=uniform num_vcs=2 injection_rate=0.13  > result_fattree_uniform_vc2 ; awk -f filter.awk result_fattree_uniform_vc2  | sort -g > result_fattree_uniform_vc2.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_ps1_vc2   topology=fattree traffic=uniform routing_function=nca  num_vcs=2  packet_size=1 > result_fattree_uniform_nca_ps1_vc2 ; awk -f filter.awk result_fattree_uniform_nca_ps1_vc2  | sort -g > result_fattree_uniform_nca_ps1_vc2.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_ps1_vc4   topology=fattree traffic=uniform routing_function=nca  num_vcs=4  packet_size=1 > result_fattree_uniform_nca_ps1_vc4 ; awk -f filter.awk result_fattree_uniform_nca_ps1_vc4  | sort -g > result_fattree_uniform_nca_ps1_vc4.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_ps1_vc8   topology=fattree traffic=uniform routing_function=nca  num_vcs=8  packet_size=1 > result_fattree_uniform_nca_ps1_vc8 ; awk -f filter.awk result_fattree_uniform_nca_ps1_vc8  | sort -g > result_fattree_uniform_nca_ps1_vc8.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_ps1_vc16  topology=fattree traffic=uniform routing_function=nca  num_vcs=16 packet_size=1 > result_fattree_uniform_nca_ps1_vc16; awk -f filter.awk result_fattree_uniform_nca_ps1_vc16 | sort -g > result_fattree_uniform_nca_ps1_vc16.1

./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps1_vc2  topology=fattree traffic=uniform routing_function=anca num_vcs=2  packet_size=1 > result_fattree_uniform_anca_ps1_vc2 ; awk -f filter.awk result_fattree_uniform_anca_ps1_vc2  | sort -g > result_fattree_uniform_anca_ps1_vc2.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps1_vc4  topology=fattree traffic=uniform routing_function=anca num_vcs=4  packet_size=1 > result_fattree_uniform_anca_ps1_vc4 ; awk -f filter.awk result_fattree_uniform_anca_ps1_vc4  | sort -g > result_fattree_uniform_anca_ps1_vc4.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps1_vc8  topology=fattree traffic=uniform routing_function=anca num_vcs=8  packet_size=1 > result_fattree_uniform_anca_ps1_vc8 ; awk -f filter.awk result_fattree_uniform_anca_ps1_vc8  | sort -g > result_fattree_uniform_anca_ps1_vc8.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps1_vc16 topology=fattree traffic=uniform routing_function=anca num_vcs=16 packet_size=1 > result_fattree_uniform_anca_ps1_vc16; awk -f filter.awk result_fattree_uniform_anca_ps1_vc16 | sort -g > result_fattree_uniform_anca_ps1_vc16.1

./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps4_vc2  topology=fattree traffic=uniform routing_function=anca num_vcs=2  packet_size=4 > result_fattree_uniform_anca_ps4_vc2 ; awk -f filter.awk result_fattree_uniform_anca_ps4_vc2  | sort -g > result_fattree_uniform_anca_ps4_vc2.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps4_vc4  topology=fattree traffic=uniform routing_function=anca num_vcs=4  packet_size=4 > result_fattree_uniform_anca_ps4_vc4 ; awk -f filter.awk result_fattree_uniform_anca_ps4_vc4  | sort -g > result_fattree_uniform_anca_ps4_vc4.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps4_vc8  topology=fattree traffic=uniform routing_function=anca num_vcs=8  packet_size=4 > result_fattree_uniform_anca_ps4_vc8 ; awk -f filter.awk result_fattree_uniform_anca_ps4_vc8  | sort -g > result_fattree_uniform_anca_ps4_vc8.1
./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_ps4_vc16 topology=fattree traffic=uniform routing_function=anca num_vcs=16 packet_size=4 > result_fattree_uniform_anca_ps4_vc16; awk -f filter.awk result_fattree_uniform_anca_ps4_vc16 | sort -g > result_fattree_uniform_anca_ps4_vc16.1

