../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_vc2  topology=fattree traffic=uniform num_vcs=2 injection_rate=0.13  > result_fattree_uniform_vc2 ; awk -f filter.awk result_fattree_uniform_vc2  | sort -g > result_fattree_uniform_vc2.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_vc2  topology=fattree traffic=uniform routing_function=nca num_vcs=2   > result_fattree_uniform_nca_vc2 ; awk -f filter.awk result_fattree_uniform_nca_vc2  | sort -g > result_fattree_uniform_nca_vc2.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_vc4  topology=fattree traffic=uniform routing_function=nca num_vcs=4   > result_fattree_uniform_nca_vc4 ; awk -f filter.awk result_fattree_uniform_nca_vc4  | sort -g > result_fattree_uniform_nca_vc4.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_vc8  topology=fattree traffic=uniform routing_function=nca num_vcs=8   > result_fattree_uniform_nca_vc8 ; awk -f filter.awk result_fattree_uniform_nca_vc8  | sort -g > result_fattree_uniform_nca_vc8.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_nca_vc16 topology=fattree traffic=uniform routing_function=nca num_vcs=16  > result_fattree_uniform_nca_vc16; awk -f filter.awk result_fattree_uniform_nca_vc16 | sort -g > result_fattree_uniform_nca_vc16.1

#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_vc2  topology=fattree traffic=uniform routing_function=anca num_vcs=2   > result_fattree_uniform_anca_vc2 ; awk -f filter.awk result_fattree_uniform_anca_vc2  | sort -g > result_fattree_uniform_anca_vc2.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_vc4  topology=fattree traffic=uniform routing_function=anca num_vcs=4   > result_fattree_uniform_anca_vc4 ; awk -f filter.awk result_fattree_uniform_anca_vc4  | sort -g > result_fattree_uniform_anca_vc4.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_vc8  topology=fattree traffic=uniform routing_function=anca num_vcs=8   > result_fattree_uniform_anca_vc8 ; awk -f filter.awk result_fattree_uniform_anca_vc8  | sort -g > result_fattree_uniform_anca_vc8.1
#./sweep.sh  ../src/booksim runfiles/ssyftree watch_out=watch_out_fattree_anca_vc16 topology=fattree traffic=uniform routing_function=anca num_vcs=16  > result_fattree_uniform_anca_vc16; awk -f filter.awk result_fattree_uniform_anca_vc16 | sort -g > result_fattree_uniform_anca_vc16.1

